// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHV_tWBg53-HsR5DDFL7WQfJrL56qvBaI',
    appId: '1:325042169664:web:78b972a71a1775611d7ca5',
    messagingSenderId: '325042169664',
    projectId: 'sawariya-7efd4',
    authDomain: 'sawariya-7efd4.firebaseapp.com',
    storageBucket: 'sawariya-7efd4.firebasestorage.app',
    measurementId: 'G-9KE6MVLHXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz0VKzg-CmNoFZz0j73dsyb_VHfwwcboo',
    appId: '1:325042169664:android:a5ba7cdfecb84c161d7ca5',
    messagingSenderId: '325042169664',
    projectId: 'sawariya-7efd4',
    storageBucket: 'sawariya-7efd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-S7xjHOctxHVSt2vYR6xhfXfxKWrot1s',
    appId: '1:325042169664:ios:706ef349bfd6673e1d7ca5',
    messagingSenderId: '325042169664',
    projectId: 'sawariya-7efd4',
    storageBucket: 'sawariya-7efd4.firebasestorage.app',
    iosBundleId: 'com.example.dairyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-S7xjHOctxHVSt2vYR6xhfXfxKWrot1s',
    appId: '1:325042169664:ios:706ef349bfd6673e1d7ca5',
    messagingSenderId: '325042169664',
    projectId: 'sawariya-7efd4',
    storageBucket: 'sawariya-7efd4.firebasestorage.app',
    iosBundleId: 'com.example.dairyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHV_tWBg53-HsR5DDFL7WQfJrL56qvBaI',
    appId: '1:325042169664:web:bbfe2d284cf6586d1d7ca5',
    messagingSenderId: '325042169664',
    projectId: 'sawariya-7efd4',
    authDomain: 'sawariya-7efd4.firebaseapp.com',
    storageBucket: 'sawariya-7efd4.firebasestorage.app',
    measurementId: 'G-NSNFKR5469',
  );
}
