/// Hindi translations for every key in app_strings_en.dart.
///
/// Natural Hindi suitable for a dairy / customer mobile application. Brand
/// names (Sawariya Dairy, product names) are kept as-is.
const Map<String, String> appStringsHi = {
  // ─── Bottom navigation / shell ───────────────────────────────────────────
  'Home': 'होम',
  'Shop': 'दुकान',
  'Orders': 'ऑर्डर',
  'Profile': 'प्रोफ़ाइल',
  'Sawariya Dairy': 'सावरिया डेयरी',
  'Search products...': 'उत्पाद खोजें...',

  // ─── Common buttons / actions ────────────────────────────────────────────
  'Save': 'सहेजें',
  'Cancel': 'रद्द करें',
  'OK': 'ठीक है',
  'Continue': 'जारी रखें',
  'Submit': 'जमा करें',
  'Retry': 'पुनः प्रयास करें',
  'View All': 'सभी देखें',
  'See All': 'सभी देखें',
  'Add': 'जोड़ें',
  'Edit': 'संपादित करें',
  'Delete': 'हटाएँ',
  'Remove': 'हटाएँ',
  'Close': 'बंद करें',
  'Confirm': 'पुष्टि करें',
  'Yes': 'हाँ',
  'No': 'नहीं',
  'Back': 'वापस',
  'Next': 'आगे',
  'Done': 'पूर्ण',
  'Skip': 'छोड़ें',
  'Get Started': 'शुरू करें',

  // ─── Common states ───────────────────────────────────────────────────────
  'Loading...': 'लोड हो रहा है...',
  'Something went wrong': 'कुछ ग़लत हो गया',
  'Please try again later.': 'कृपया बाद में पुनः प्रयास करें।',
  'No products found': 'कोई उत्पाद नहीं मिला',
  'No products match your filter. Try adjusting or reset.':
      'आपके फ़िल्टर से कोई उत्पाद मेल नहीं खाता। फ़िल्टर बदलें या रीसेट करें।',
  'Reset Filters': 'फ़िल्टर रीसेट करें',
  'No orders yet': 'अभी कोई ऑर्डर नहीं है',
  'No notifications yet': 'अभी कोई सूचना नहीं है',
  'Your cart is empty': 'आपका कार्ट खाली है',

  // ─── Auth ────────────────────────────────────────────────────────────────
  'Welcome Back': 'वापसी पर स्वागत है',
  'Login to continue ordering fresh dairy products':
      'ताज़ा डेयरी उत्पाद ऑर्डर करना जारी रखने के लिए लॉगिन करें',
  'Phone Number': 'फ़ोन नंबर',
  'Enter your mobile number': 'अपना मोबाइल नंबर दर्ज करें',
  'Send OTP': 'OTP भेजें',
  'Or': 'या',
  'Create Account': 'खाता बनाएँ',
  'New here? ': 'नए हैं? ',
  'Sign Up': 'साइन अप करें',
  'Full Name': 'पूरा नाम',
  'Email': 'ईमेल',
  'Password': 'पासवर्ड',
  'Forgot Password?': 'पासवर्ड भूल गए?',
  'Verify & Continue': 'सत्यापित करें और जारी रखें',
  'Resend OTP': 'OTP फिर से भेजें',
  'Enter OTP': 'OTP दर्ज करें',
  "We've sent a 6-digit code to": 'हमने 6-अंकीय कोड भेजा है',
  'Wrong number? ': 'गलत नंबर? ',
  'Change': 'बदलें',
  'Reset Password': 'पासवर्ड रीसेट करें',
  'New Password': 'नया पासवर्ड',
  'Confirm Password': 'पासवर्ड की पुष्टि करें',
  'Terms & Conditions': 'नियम और शर्तें',
  'Privacy Policy': 'गोपनीयता नीति',

  // ─── Home ────────────────────────────────────────────────────────────────
  'Categories': 'श्रेणियाँ',
  'Farm fresh dairy essentials delivered daily':
      'रोज़ाना ताज़े डेयरी उत्पाद, सीधे आपके घर तक',
  'Fresh Deals': 'ताज़े ऑफ़र',
  'Best Sellers': 'सबसे लोकप्रिय',
  'A2 Cow Milk': 'A2 गाय का दूध',
  'Pure Goodness, Delivered to Your Doorstep':
      'शुद्ध अच्छाई, सीधे आपके दरवाज़े तक',
  'Track Your Order': 'अपना ऑर्डर ट्रैक करें',
  'Enter Order ID': 'ऑर्डर आईडी दर्ज करें',
  'Why Choose Sawariya Dairy?': 'सावरिया डेयरी ही क्यों?',
  '100% Pure & Natural': '100% शुद्ध और प्राकृतिक',
  'Farm Fresh Daily': 'रोज़ फार्म फ्रेश',
  'Doorstep Delivery': 'घर तक डिलीवरी',
  'No Preservatives': 'कोई प्रिज़र्वेटिव नहीं',

  // ─── Shop / Product ──────────────────────────────────────────────────────
  'All': 'सभी',
  'Milk': 'दूध',
  'Curd': 'दही',
  'Paneer': 'पनीर',
  'Ghee': 'घी',
  'Butter': 'मक्खन',
  'Lassi': 'लस्सी',
  'Add to Cart': 'कार्ट में जोड़ें',
  'Go to Cart': 'कार्ट पर जाएँ',
  'Product Details': 'उत्पाद विवरण',
  'Description': 'विवरण',
  'Reviews': 'समीक्षाएँ',
  'Related Products': 'संबंधित उत्पाद',
  'Out of Stock': 'स्टॉक खत्म',
  'In Stock': 'स्टॉक में',
  'per': 'प्रति',
  'Quantity': 'मात्रा',

  // ─── Cart / Checkout ─────────────────────────────────────────────────────
  'Cart': 'कार्ट',
  'Checkout': 'चेकआउट',
  'Subtotal': 'उप-योग',
  'Delivery Charge': 'डिलीवरी शुल्क',
  'Discount': 'छूट',
  'Total': 'कुल',
  'Grand Total': 'कुल राशि',
  'To Pay': 'देय राशि',
  'Proceed to Checkout': 'चेकआउट करें',
  'Place Order': 'ऑर्डर करें',
  'Delivery Address': 'डिलीवरी पता',
  'Payment Method': 'भुगतान का तरीका',
  'Cash on Delivery': 'कैश ऑन डिलीवरी',
  'Order Summary': 'ऑर्डर सारांश',
  'Free delivery on orders above ₹500': '₹500 से ऊपर के ऑर्डर पर मुफ़्त डिलीवरी',
  'Clear Cart': 'कार्ट खाली करें',
  'Start Shopping': 'खरीदारी शुरू करें',

  // ─── Orders ──────────────────────────────────────────────────────────────
  'My Orders': 'मेरे ऑर्डर',
  'Order Details': 'ऑर्डर विवरण',
  'Order ID': 'ऑर्डर आईडी',
  'Order Date': 'ऑर्डर की तारीख',
  'Order Status': 'ऑर्डर स्थिति',
  'Track Order': 'ऑर्डर ट्रैक करें',
  'Cancel Order': 'ऑर्डर रद्द करें',
  'Reorder': 'दोबारा ऑर्डर करें',
  'Pending': 'लंबित',
  'Confirmed': 'पुष्ट',
  'Preparing': 'तैयार हो रहा है',
  'Out for Delivery': 'डिलीवरी के लिए निकला',
  'Delivered': 'डिलीवर हो गया',
  'Cancelled': 'रद्द',
  'Items': 'आइटम',
  'Item': 'आइटम',
  'Shipping Address': 'डिलीवरी पता',
  'Payment': 'भुगतान',
  'Paid': 'भुगतान हो गया',
  'Unpaid': 'भुगतान बाकी',
  'All Orders': 'सभी ऑर्डर',
  'Active': 'सक्रिय',
  'History': 'इतिहास',

  // ─── Profile ─────────────────────────────────────────────────────────────
  'My Profile': 'मेरी प्रोफ़ाइल',
  'Manage your personal details': 'अपनी व्यक्तिगत जानकारी प्रबंधित करें',
  'Edit Profile': 'प्रोफ़ाइल संपादित करें',
  'Delivery Addresses': 'डिलीवरी पते',
  'Add or edit delivery addresses': 'डिलीवरी पते जोड़ें या संपादित करें',
  'Manage your payment options': 'अपने भुगतान विकल्प प्रबंधित करें',
  'My Subscriptions': 'मेरी सदस्यताएँ',
  'Manage milk & product subscriptions': 'दूध और उत्पाद सदस्यता प्रबंधित करें',
  'Notifications': 'सूचनाएँ',
  'Manage your notification preferences': 'अपनी सूचना प्राथमिकताएँ प्रबंधित करें',
  'About Sawariya Dairy': 'सावरिया डेयरी के बारे में',
  'Know more about us': 'हमारे बारे में और जानें',
  'Language': 'भाषा',
  'English': 'अंग्रेज़ी',
  'Hindi': 'हिंदी',
  'System Default': 'सिस्टम डिफ़ॉल्ट',
  'Logout': 'लॉग आउट',
  'Log out of your account': 'अपने खाते से लॉग आउट करें',
  'Log Out': 'लॉग आउट',
  'Are you sure you want to log out of Sawariya Dairy?':
      'क्या आप वाकई सावरिया डेयरी से लॉग आउट करना चाहते हैं?',
  'Account Settings': 'खाता सेटिंग्स',
  'Fresh Member': 'फ्रेश सदस्य',
  'Open Delivery Panel': 'डिलीवरी पैनल खोलें',
  'Switch to delivery experience': 'डिलीवरी अनुभव पर जाएँ',
  'Select Language': 'भाषा चुनें',
  'Choose your preferred language': 'अपनी पसंदीदा भाषा चुनें',
  'Profile updated successfully': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई',
  'Name': 'नाम',
  'Mobile Number': 'मोबाइल नंबर',
  'Date of Birth': 'जन्म तिथि',
  'Gender': 'लिंग',
  'Male': 'पुरुष',
  'Female': 'महिला',
  'Other': 'अन्य',

  // ─── Address ─────────────────────────────────────────────────────────────
  'Address': 'पता',
  'Add Address': 'पता जोड़ें',
  'Add New Address': 'नया पता जोड़ें',
  'Edit Address': 'पता संपादित करें',
  'Saved Addresses': 'सहेजे गए पते',
  'No addresses saved yet': 'अभी कोई पता सहेजा नहीं गया है',
  'Add a new address to get started': 'शुरू करने के लिए नया पता जोड़ें',
  'House / Flat / Block No.': 'मकान / फ्लैट / ब्लॉक नंबर',
  'Street / Area / Locality': 'गली / क्षेत्र / मोहल्ला',
  'City': 'शहर',
  'State': 'राज्य',
  'Pin Code': 'पिन कोड',
  'Full Name (Contact Person)': 'पूरा नाम (संपर्क व्यक्ति)',
  'Label (e.g. Home, Work)': 'लेबल (जैसे घर, कार्यालय)',
  'Set as default address': 'डिफ़ॉल्ट पता बनाएँ',
  'Default': 'डिफ़ॉल्ट',
  'Address saved successfully': 'पता सफलतापूर्वक सहेजा गया',
  'Address deleted': 'पता हटा दिया गया',
  'Please fill all required fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',

  // ─── Notifications ───────────────────────────────────────────────────────
  'Mark all as read': 'सभी को पढ़ा हुआ मार्क करें',
  'All caught up!': 'सब देख लिया!',
  "You don't have any notifications right now.":
      'अभी आपके पास कोई सूचना नहीं है।',

  // ─── About ───────────────────────────────────────────────────────────────
  'Our Story': 'हमारी कहानी',
  'Contact Us': 'संपर्क करें',
  'Version': 'संस्करण',
  'Call Us': 'कॉल करें',
  'Email Us': 'ईमेल करें',
  'Visit Website': 'वेबसाइट देखें',

  // ─── Delivery panel ──────────────────────────────────────────────────────
  'App Settings': 'ऐप सेटिंग्स',
  'Navigation': 'नेविगेशन',
  'Google Maps': 'गूगल मैप्स',
  'Apple Maps': 'ऐपल मैप्स',
  'Waze': 'वेज़',
  'Online': 'ऑनलाइन',
  'Offline': 'ऑफ़लाइन',
  'You are currently offline': 'आप अभी ऑफ़लाइन हैं',
  'You are online and receiving orders': 'आप ऑनलाइन हैं और ऑर्डर मिल रहे हैं',
  'Earnings': 'कमाई',
  'Today': 'आज',
  'This Week': 'इस सप्ताह',
  'This Month': 'इस महीने',
  'Requests': 'अनुरोध',
  'Active Deliveries': 'सक्रिय डिलीवरी',
  'Delivery History': 'डिलीवरी इतिहास',
  'Accept': 'स्वीकार करें',
  'Decline': 'अस्वीकार करें',
  'Mark as Delivered': 'डिलीवर होने पर मार्क करें',
  'Start Delivery': 'डिलीवरी शुरू करें',
  'Navigate': 'रास्ता दिखाएँ',
  'Call Customer': 'ग्राहक को कॉल करें',
  'No pending requests': 'कोई लंबित अनुरोध नहीं',
  'New delivery requests will appear here':
      'नए डिलीवरी अनुरोध यहाँ दिखाई देंगे',

  // ─── App bar ──────────────────────────────────────────────────────────────
  'Good morning, 👋': 'सुप्रभात, 👋',
  'Good afternoon, 👋': 'शुभ अपराह्न, 👋',
  'Good evening, 👋': 'शुभ संध्या, 👋',
  'Fresh dairy, delivered daily!': 'ताज़ा डेयरी, रोज़ डिलीवरी!',
  'Search milk, curd, paneer, ghee...': 'दूध, दही, पनीर, घी खोजें...',
  'Deliver to': 'डिलीवरी कहाँ',
  'Sawariya Customer': 'सावरिया ग्राहक',

  // ─── Home extras ──────────────────────────────────────────────────────────
  'Customer favorites delivered fresh daily':
      'ग्राहकों की पसंदीदा ताज़ी डेली डिलीवरी',
  'Real-time updates on your fresh delivery':
      'ताज़ी डिलीवरी पर रीयल-टाइम अपडेट',
  'Farm fresh milk & dairy products,\nhygienically packed for your family.':
      'फार्म फ्रेश दूध और डेयरी उत्पाद,\nआपके परिवार के लिए स्वच्छतापूर्वक पैक किए गए',
  '100%\nPure': '100%\nशुद्ध',
  'No Added\nPreservatives': 'कोई प्रिज़र्वेटिव\nनहीं मिला',
  'Hygienically\nPacked': 'स्वच्छतापूर्वक\nपैक किया',
  'Trusted by\nThousands': 'हज़ारों द्वारा\nविश्वसनीय',
  'Freshness You Can Trust': 'ताज़गी जिस पर भरोसा करें',
  'Sawariya Dairy Specials': 'सावरिया डेयरी विशेष',
  'Enter your Order ID': 'अपनी ऑर्डर आईडी दर्ज करें',
  'FSSAI Certified': 'FSSAI प्रमाणित',
  'Safe & Certified': 'सुरक्षित और प्रमाणित',
  'Free Delivery': 'मुफ़्त डिलीवरी',
  'On all orders': 'सभी ऑर्डर पर',
  'Same-Day Fresh': 'उसी दिन ताज़ा',
  'Timely & Fresh': 'समय पर और ताज़ा',
  'Easy Returns': 'आसान रिटर्न',
  'Hassle-free returns': 'बिना परेशानी रिटर्न',

  // ─── Price summary ────────────────────────────────────────────────────────
  'Order Bill Summary': 'ऑर्डर बिल सारांश',
  'Item Subtotal': 'आइटम उप-योग',
  'FREE': 'मुफ़्त',
  'Special Offer Discount (10%)': 'विशेष ऑफ़र छूट (10%)',
  'more for FREE delivery!': 'और मुफ़्त डिलीवरी के लिए!',
  'Place Order Now': 'अभी ऑर्डर करें',

  // ─── Payment options ──────────────────────────────────────────────────────
  'Cash on Delivery (COD)': 'कैश ऑन डिलीवरी (COD)',
  'Online Payment (UPI / Cards / NetBanking)':
      'ऑनलाइन भुगतान (UPI / कार्ड / नेटबैंकिंग)',
  'Pay cash or UPI upon fresh delivery at your doorstep':
      'दरवाज़े पर ताज़ी डिलीवरी पर कैश या UPI से भुगतान करें',
  'Instant 100% secure payment via GPay, PhonePe, Paytm or Card':
      'GPay, PhonePe, Paytm या कार्ड से तुरंत 100% सुरक्षित भुगतान',

  // ─── Cart extras ──────────────────────────────────────────────────────────
  'Qty': 'मात्रा',

  // ─── Desktop sidebar ──────────────────────────────────────────────────────
  'Pure Milk. Pure Trust.': 'शुद्ध दूध। शुद्ध भरोसा।',

  // ─── Settings screen extras ───────────────────────────────────────────────
  'Manage notification preferences': 'सूचना प्राथमिकताएँ प्रबंधित करें',
  'Push Notifications': 'पुश सूचनाएँ',
  'Order & delivery alerts on this device':
      'इस डिवाइस पर ऑर्डर और डिलीवरी अलर्ट',
  'Email Notifications': 'ईमेल सूचनाएँ',
  'Summary & promotional emails': 'सारांश और प्रचार ईमेल',
  'Preferences': 'प्राथमिकताएँ',
  'Theme': 'थीम',
  'Default Navigation App': 'डिफ़ॉल्ट नेविगेशन ऐप',
  'Light': 'लाइट',
  'Dark': 'डार्क',

  // ─── Profile screen extras ────────────────────────────────────────────────
  'Delivery Partner': 'डिलीवरी पार्टनर',
  'Payment Methods': 'भुगतान के तरीके',
  'Processing': 'प्रोसेसिंग',

  // ─── Delivery panel profile tab extras ────────────────────────────────────
  'Rating': 'रेटिंग',
  "Today's Deliveries": 'आज की डिलीवरी',
  "Today's Earnings": 'आज की कमाई',
  'Details': 'विवरण',
  'Phone': 'फ़ोन',
  'Vehicle': 'वाहन',
  'Assigned Zone': 'नियुक्त क्षेत्र',
  'Partner ID': 'पार्टनर आईडी',
  'Duty Status': 'ड्यूटी स्थिति',
  'Currently Online': 'वर्तमान में ऑनलाइन',
  'Currently Offline': 'वर्तमान में ऑफ़लाइन',
  "You're receiving delivery requests": 'आपको डिलीवरी अनुरोध मिल रहे हैं',
  'Go online to start receiving requests':
      'अनुरोध प्राप्त करने के लिए ऑनलाइन हों',
  'Are you sure you want to logout?': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
  "You'll receive delivery requests for your assigned zone. Tap \"Accept\" to start a delivery.":
      'आपको अपने नियुक्त क्षेत्र के लिए डिलीवरी अनुरोध मिलेंगे। डिलीवरी शुरू करने के लिए "स्वीकार करें" टैप करें।',

  // ─── Checkout extras ──────────────────────────────────────────────────────
  'Checkout & Order Review': 'चेकआउट और ऑर्डर समीक्षा',
  'Change Address': 'पता बदलें',
  'No delivery address selected.': 'कोई डिलीवरी पता चयनित नहीं।',
  'Order Items': 'ऑर्डर आइटम',
  'Products': 'उत्पाद',
  'Back to Home Feed': 'होम फ़ीड पर वापस',

  // ─── Onboarding ───────────────────────────────────────────────────────────
  'Fresh Dairy, Every Day': 'ताज़ा डेयरी, हर दिन',
  'Enjoy fresh and quality dairy products delivered with care from Sawariya Dairy.':
      'सावरिया डेयरी से ताज़े और गुणवत्तापूर्ण डेयरी उत्पादों का आनंद लें, देखभाल के साथ डिलीवर किए गए।',
  'Pure Products, Trusted Quality': 'शुद्ध उत्पाद, विश्वसनीय गुणवत्ता',
  'Every product is sourced fresh, hygienically packed and quality-checked to bring you the best of Sawariya Dairy.':
      'हर उत्पाद ताज़ा स्रोतों से लिया गया है, स्वच्छतापूर्वक पैक किया गया है और गुणवत्ता जांचा गया है।',
  'Simple Shopping, Fresh Delivery': 'सरल खरीदारी, ताज़ी डिलीवरी',
  'Discover your favorite dairy products, order easily and enjoy freshness at your doorstep.':
      'अपने पसंदीदा डेयरी उत्पाद खोजें, आसानी से ऑर्डर करें और दरवाज़े पर ताज़गी का आनंद लें।',
};
