/// English → user-facing string registry.
///
/// Keys are the canonical English strings. This map is the single source of
/// truth for every localized string used via [tr]. The Hindi map
/// (app_strings_hi.dart) must keep the same keys.
const Map<String, String> appStringsEn = {
  // ─── Bottom navigation / shell ───────────────────────────────────────────
  'Home': 'Home',
  'Shop': 'Shop',
  'Orders': 'Orders',
  'Profile': 'Profile',
  'Sawariya Dairy': 'Sawariya Dairy',
  'Search products...': 'Search products...',

  // ─── Common buttons / actions ────────────────────────────────────────────
  'Save': 'Save',
  'Cancel': 'Cancel',
  'OK': 'OK',
  'Continue': 'Continue',
  'Submit': 'Submit',
  'Retry': 'Retry',
  'View All': 'View All',
  'See All': 'See All',
  'Add': 'Add',
  'Edit': 'Edit',
  'Delete': 'Delete',
  'Remove': 'Remove',
  'Close': 'Close',
  'Confirm': 'Confirm',
  'Yes': 'Yes',
  'No': 'No',
  'Back': 'Back',
  'Next': 'Next',
  'Done': 'Done',
  'Skip': 'Skip',
  'Get Started': 'Get Started',

  // ─── Common states ───────────────────────────────────────────────────────
  'Loading...': 'Loading...',
  'Something went wrong': 'Something went wrong',
  'Please try again later.': 'Please try again later.',
  'No products found': 'No products found',
  'No products match your filter. Try adjusting or reset.':
      'No products match your filter. Try adjusting or reset.',
  'Reset Filters': 'Reset Filters',
  'No orders yet': 'No orders yet',
  'No notifications yet': 'No notifications yet',
  'Your cart is empty': 'Your cart is empty',

  // ─── Auth ────────────────────────────────────────────────────────────────
  'Welcome Back': 'Welcome Back',
  'Login to continue ordering fresh dairy products':
      'Login to continue ordering fresh dairy products',
  'Phone Number': 'Phone Number',
  'Enter your mobile number': 'Enter your mobile number',
  'Send OTP': 'Send OTP',
  'Or': 'Or',
  'Create Account': 'Create Account',
  'New here? ': 'New here? ',
  'Sign Up': 'Sign Up',
  'Full Name': 'Full Name',
  'Email': 'Email',
  'Password': 'Password',
  'Forgot Password?': 'Forgot Password?',
  'Verify & Continue': 'Verify & Continue',
  'Resend OTP': 'Resend OTP',
  'Enter OTP': 'Enter OTP',
  "We've sent a 6-digit code to": "We've sent a 6-digit code to",
  'Wrong number? ': 'Wrong number? ',
  'Change': 'Change',
  'Reset Password': 'Reset Password',
  'New Password': 'New Password',
  'Confirm Password': 'Confirm Password',
  'Terms & Conditions': 'Terms & Conditions',
  'Privacy Policy': 'Privacy Policy',

  // ─── Home ────────────────────────────────────────────────────────────────
  'Categories': 'Categories',
  'Farm fresh dairy essentials delivered daily':
      'Farm fresh dairy essentials delivered daily',
  'Fresh Deals': 'Fresh Deals',
  'Best Sellers': 'Best Sellers',
  'A2 Cow Milk': 'A2 Cow Milk',
  'Pure Goodness, Delivered to Your Doorstep':
      'Pure Goodness, Delivered to Your Doorstep',
  'Track Your Order': 'Track Your Order',
  'Enter Order ID': 'Enter Order ID',
  'Why Choose Sawariya Dairy?': 'Why Choose Sawariya Dairy?',
  '100% Pure & Natural': '100% Pure & Natural',
  'Farm Fresh Daily': 'Farm Fresh Daily',
  'Doorstep Delivery': 'Doorstep Delivery',
  'No Preservatives': 'No Preservatives',

  // ─── Shop / Product ──────────────────────────────────────────────────────
  'All': 'All',
  'Milk': 'Milk',
  'Curd': 'Curd',
  'Paneer': 'Paneer',
  'Ghee': 'Ghee',
  'Butter': 'Butter',
  'Lassi': 'Lassi',
  'Add to Cart': 'Add to Cart',
  'Go to Cart': 'Go to Cart',
  'Product Details': 'Product Details',
  'Description': 'Description',
  'Reviews': 'Reviews',
  'Related Products': 'Related Products',
  'Out of Stock': 'Out of Stock',
  'In Stock': 'In Stock',
  'per': 'per',
  'Quantity': 'Quantity',

  // ─── Cart / Checkout ─────────────────────────────────────────────────────
  'Cart': 'Cart',
  'Checkout': 'Checkout',
  'Subtotal': 'Subtotal',
  'Delivery Charge': 'Delivery Charge',
  'Discount': 'Discount',
  'Total': 'Total',
  'Grand Total': 'Grand Total',
  'To Pay': 'To Pay',
  'Proceed to Checkout': 'Proceed to Checkout',
  'Place Order': 'Place Order',
  'Delivery Address': 'Delivery Address',
  'Payment Method': 'Payment Method',
  'Cash on Delivery': 'Cash on Delivery',
  'Order Summary': 'Order Summary',
  'Free delivery on orders above ₹500': 'Free delivery on orders above ₹500',
  'Clear Cart': 'Clear Cart',
  'Start Shopping': 'Start Shopping',

  // ─── Orders ──────────────────────────────────────────────────────────────
  'My Orders': 'My Orders',
  'Order Details': 'Order Details',
  'Order ID': 'Order ID',
  'Order Date': 'Order Date',
  'Order Status': 'Order Status',
  'Track Order': 'Track Order',
  'Cancel Order': 'Cancel Order',
  'Reorder': 'Reorder',
  'Pending': 'Pending',
  'Confirmed': 'Confirmed',
  'Preparing': 'Preparing',
  'Out for Delivery': 'Out for Delivery',
  'Delivered': 'Delivered',
  'Cancelled': 'Cancelled',
  'Items': 'Items',
  'Item': 'Item',
  'Shipping Address': 'Shipping Address',
  'Payment': 'Payment',
  'Paid': 'Paid',
  'Unpaid': 'Unpaid',
  'All Orders': 'All Orders',
  'Active': 'Active',
  'History': 'History',

  // ─── Profile ─────────────────────────────────────────────────────────────
  'My Profile': 'My Profile',
  'Manage your personal details': 'Manage your personal details',
  'Edit Profile': 'Edit Profile',
  'Delivery Addresses': 'Delivery Addresses',
  'Add or edit delivery addresses': 'Add or edit delivery addresses',
  'Manage your payment options': 'Manage your payment options',
  'My Subscriptions': 'My Subscriptions',
  'Manage milk & product subscriptions': 'Manage milk & product subscriptions',
  'Notifications': 'Notifications',
  'Manage your notification preferences': 'Manage your notification preferences',
  'About Sawariya Dairy': 'About Sawariya Dairy',
  'Know more about us': 'Know more about us',
  'Language': 'Language',
  'English': 'English',
  'Hindi': 'Hindi',
  'System Default': 'System Default',
  'Logout': 'Logout',
  'Log out of your account': 'Log out of your account',
  'Log Out': 'Log Out',
  'Are you sure you want to log out of Sawariya Dairy?':
      'Are you sure you want to log out of Sawariya Dairy?',
  'Account Settings': 'Account Settings',
  'Fresh Member': 'Fresh Member',
  'Open Delivery Panel': 'Open Delivery Panel',
  'Switch to delivery experience': 'Switch to delivery experience',
  'Select Language': 'Select Language',
  'Choose your preferred language': 'Choose your preferred language',
  'Profile updated successfully': 'Profile updated successfully',
  'Name': 'Name',
  'Mobile Number': 'Mobile Number',
  'Date of Birth': 'Date of Birth',
  'Gender': 'Gender',
  'Male': 'Male',
  'Female': 'Female',
  'Other': 'Other',

  // ─── Address ─────────────────────────────────────────────────────────────
  'Address': 'Address',
  'Add Address': 'Add Address',
  'Add New Address': 'Add New Address',
  'Edit Address': 'Edit Address',
  'Saved Addresses': 'Saved Addresses',
  'No addresses saved yet': 'No addresses saved yet',
  'Add a new address to get started': 'Add a new address to get started',
  'House / Flat / Block No.': 'House / Flat / Block No.',
  'Street / Area / Locality': 'Street / Area / Locality',
  'City': 'City',
  'State': 'State',
  'Pin Code': 'Pin Code',
  'Full Name (Contact Person)': 'Full Name (Contact Person)',
  'Label (e.g. Home, Work)': 'Label (e.g. Home, Work)',
  'Set as default address': 'Set as default address',
  'Default': 'Default',
  'Address saved successfully': 'Address saved successfully',
  'Address deleted': 'Address deleted',
  'Please fill all required fields': 'Please fill all required fields',

  // ─── Notifications ───────────────────────────────────────────────────────
  'Mark all as read': 'Mark all as read',
  'All caught up!': 'All caught up!',
  "You don't have any notifications right now.":
      "You don't have any notifications right now.",

  // ─── About ───────────────────────────────────────────────────────────────
  'Our Story': 'Our Story',
  'Contact Us': 'Contact Us',
  'Version': 'Version',
  'Call Us': 'Call Us',
  'Email Us': 'Email Us',
  'Visit Website': 'Visit Website',

  // ─── Delivery panel ──────────────────────────────────────────────────────
  'App Settings': 'App Settings',
  'Navigation': 'Navigation',
  'Google Maps': 'Google Maps',
  'Apple Maps': 'Apple Maps',
  'Waze': 'Waze',
  'Online': 'Online',
  'Offline': 'Offline',
  'You are currently offline': 'You are currently offline',
  'You are online and receiving orders': 'You are online and receiving orders',
  'Earnings': 'Earnings',
  'Today': 'Today',
  'This Week': 'This Week',
  'This Month': 'This Month',
  'Requests': 'Requests',
  'Active Deliveries': 'Active Deliveries',
  'Delivery History': 'Delivery History',
  'Accept': 'Accept',
  'Decline': 'Decline',
  'Mark as Delivered': 'Mark as Delivered',
  'Start Delivery': 'Start Delivery',
  'Navigate': 'Navigate',
  'Call Customer': 'Call Customer',
  'No pending requests': 'No pending requests',
  'New delivery requests will appear here':
      'New delivery requests will appear here',
};
